import type { Metadata } from 'next'
import './globals.css'

import Header from '#components/ui/header'

export const metadata: Metadata = {
  title: 'Carbon Exchanges',
  description: 'Generated by create gwjun app',
  // icons: {
  //   icon: '',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className="bg-white text-gray-900 tracking-tight">
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
